# permissions for end users to view faultinjections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: faultinjection-viewer-role
rules:
- apiGroups:
  - resiliency.grainger.com
  resources:
  - faultinjections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resiliency.grainger.com
  resources:
  - faultinjections/status
  verbs:
  - get
