# permissions for end users to edit faultinjections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: faultinjection-editor-role
rules:
- apiGroups:
  - resiliency.grainger.com
  resources:
  - faultinjections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resiliency.grainger.com
  resources:
  - faultinjections/status
  verbs:
  - get
